import SandboxedIframe from "./SandboxedIframe";

interface Props {
  html: string;
}

export default function ArtifactViewer({ html }: Props) {
  return (
    <div>
      <h3 style={{ marginTop: 0 }}>Artifact Viewer</h3>

      <p style={{ color: "#64748b", fontSize: 14 }}>
        HTML artifacts generated by the assistant.
      </p>

      <SandboxedIframe html={html} />
    </div>
  );
}